apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: iamalihdr116/clientup:3  # Replace with the image built from your client Dockerfile
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: client
  namespace: myapp
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: client