apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: my-app-image
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: maindb
              key: mysqlcrud
