name: Test and Deploy to Minikube

on:
  push:
    branches:
      - main  

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Check out code
        uses: actions/checkout@v2

      # Step 2: Snyk Vulnerability Scan (Server)
      - name: Snyk Code and Dependency Scan (Server)
        uses: snyk/actions/node@master
        with:
          command: test
          args: server
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Step 3: Snyk Vulnerability Scan (Client)
      - name: Snyk Code and Dependency Scan (Client)
        uses: snyk/actions/node@
